"""empty message

Revision ID: 110845046b32
Revises: 6af5a13ade17
Create Date: 2018-09-15 13:31:44.839220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110845046b32'
down_revision = '6af5a13ade17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_photo')
    op.add_column('user', sa.Column('profile_photo', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_photo')
    op.create_table('profile_photo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profile_photo_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_photo_pkey')
    )
    # ### end Alembic commands ###
