"""sub_race

Revision ID: c04765b1e8f3
Revises: 9dd6a13c5a5f
Create Date: 2018-09-13 17:31:53.543751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04765b1e8f3'
down_revision = '9dd6a13c5a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub__race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub__race')
    # ### end Alembic commands ###
