"""sub_class

Revision ID: e45d179078b7
Revises: c04765b1e8f3
Create Date: 2018-09-13 19:11:47.836186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45d179078b7'
down_revision = 'c04765b1e8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub__class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_class', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub__class')
    # ### end Alembic commands ###
